const dummyData = [
  {
    id: 1,
    name: "Jon",
    email: "jon@gmail.com",
    password: "12345678",
    gender: "male",
    phone: "1112131415",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "Javascript",
  },
  {
    id: 2,
    name: "Doe",
    email: "doe@gmail.com",
    password: "12345678",
    gender: "male",
    phone: "1115232343",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "React",
  },
  {
    id: 3,
    name: "Lisa",
    email: "lisa@gmail.com",
    password: "12345678",
    gender: "female",
    phone: "1112131414",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "Node JS",
  },
  {
    id: 4,
    name: "Dhoni",
    email: "dhoni@gmail.com",
    password: "12345678",
    gender: "male",
    phone: "1112131411",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "Express JS",
  },
  {
    id: 5,
    name: "Shivanya",
    email: "shivanya@gmail.com",
    password: "12345678",
    gender: "female",
    phone: "1112133415",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "Node JS",
  },
  {
    id: 6,
    name: "Don",
    email: "don@gmail.com",
    password: "12345678",
    gender: "male",
    phone: "1112131415",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "Express JS",
  },
  {
    id: 7,
    name: "Lion",
    email: "lion@gmail.com",
    password: "12345678",
    gender: "male",
    phone: "1115232343",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "Node JS",
  },
  {
    id: 8,
    name: "Kristen",
    email: "kris@gmail.com",
    password: "12345678",
    gender: "female",
    phone: "1113131414",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "React",
  },
  {
    id: 9,
    name: "Kohli",
    email: "kohli@gmail.com",
    password: "12345678",
    gender: "male",
    phone: "1112131411",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "Javascript",
  },
  {
    id: 10,
    name: "Anushka",
    email: "anu@gmail.com",
    password: "12345678",
    gender: "female",
    phone: "1112133415",
    city: "Ahmedabad",
    state: "Gujarat",
    country: "India",
    courses: "React",
  },
];
export default dummyData;
